require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hrm_sessions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HrmSession. As you add validations to HrmSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HrmSession.create! valid_attributes
      get hrm_sessions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hrm_session = HrmSession.create! valid_attributes
      get hrm_session_url(hrm_session)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hrm_session_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      hrm_session = HrmSession.create! valid_attributes
      get edit_hrm_session_url(hrm_session)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HrmSession" do
        expect {
          post hrm_sessions_url, params: { hrm_session: valid_attributes }
        }.to change(HrmSession, :count).by(1)
      end

      it "redirects to the created hrm_session" do
        post hrm_sessions_url, params: { hrm_session: valid_attributes }
        expect(response).to redirect_to(hrm_session_url(HrmSession.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HrmSession" do
        expect {
          post hrm_sessions_url, params: { hrm_session: invalid_attributes }
        }.to change(HrmSession, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hrm_sessions_url, params: { hrm_session: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hrm_session" do
        hrm_session = HrmSession.create! valid_attributes
        patch hrm_session_url(hrm_session), params: { hrm_session: new_attributes }
        hrm_session.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hrm_session" do
        hrm_session = HrmSession.create! valid_attributes
        patch hrm_session_url(hrm_session), params: { hrm_session: new_attributes }
        hrm_session.reload
        expect(response).to redirect_to(hrm_session_url(hrm_session))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hrm_session = HrmSession.create! valid_attributes
        patch hrm_session_url(hrm_session), params: { hrm_session: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hrm_session" do
      hrm_session = HrmSession.create! valid_attributes
      expect {
        delete hrm_session_url(hrm_session)
      }.to change(HrmSession, :count).by(-1)
    end

    it "redirects to the hrm_sessions list" do
      hrm_session = HrmSession.create! valid_attributes
      delete hrm_session_url(hrm_session)
      expect(response).to redirect_to(hrm_sessions_url)
    end
  end
end
